root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./cmd/govid/main.go"
bin = "./tmp/main"
full_bin = "./tmp/main"
watch = ["cmd", "internal"]
exclude_regex = ["_test.go"]
exclude_dir = ["tmp", "uploads", ".git"]
